---
title: "Assignment 1: Introduction"
author: "Student Name"
output: pdf_document
geometry: margin=2.54cm
---

## OVERVIEW

This exercise accompanies the introductory material in Environmental Data Analytics. 

## Directions
1. Change "Student Name" on line 3 (above) with your name.
3. Work through the steps, **creating code and output** that fulfill each instruction.
4. Be sure to **answer the questions** in this assignment document.
6. When you have completed the assignment, **Knit** the text and code into a single PDF file.
8. After Knitting, submit the completed exercise (PDF file) to the dropbox in Sakai. Add your last name into the file name (e.g., "Lima_A01_Introduction.Rmd") prior to submission.

The completed exercise is due on <>.

## 1) Discussion Questions

1. What are your previous experiences with data analytics, R, and Git? Include both formal and informal training.

> Answer: I have been learning and using R for data analysis for about 2 years. At first, I was learning it by myself with the help of online blogs and videos. Half a year later, I started to take a formal *Ecological Data Analysis* class that included some application of models conducted by R. And for last semester, I took ENV710, which to some ectent is quite similar to the previous *Ecological Data Analysis* class (mostly the statistics part). In a word, my previous process of learning R is more about problem solving and has no solid foundation, which means I often need to look up some very simple functions when doing data cleaning. As for Github, I only have experience downloading packages and scripts.

2. Are there any components of the course about which you feel confident?

> Answer: I am confident with my familarity wiht RStudio.

3. Are there any components of the course about which you feel apprehensive?

> Answer: I am not so familiar with other languages (like html or python) and network architecture.


## 2) GitHub

Provide a link below to your forked course repository in GitHub. Make sure you have pulled all recent changes from the course repository  and that you have updated your course README file. 

> Answer: https://github.com/AltheaL55/Environmental_Data_Analytics_2022


